# This file is currently used only to configure the black Python code
# formatter, rather than provide project metadata (see
# https://www.python.org/dev/peps/pep-0621/) which can be found instead
# in the setup.py file.

# To run the black checker with this configuration, execute 'black .' in the
# root of this repository. See https://black.readthedocs.io/en/stable/ for
# the 'black' documentation.
[tool.black]
line-length = 79

[tool.isort]
# Set for compatibility of 'black' and 'isort' auto-formatting tools
profile = "black"
# ... and since we set this against the black default line length:
line_length=79
# Prevent isort from auto-formatting '__init__.py' file imports because
# they require a specific non-alphabetical (etc.) ordering else they will
# cause errors due to bad or circular importing across the modules. Also
# skip the recipes, since we have a certain import order there for clarity
# and to avoid incompatibilities with some matplotlib and esmpy versions
# which can cause a seg fault if cf-plot/matplotlib is imported first.
extend_skip_glob = [
  "**/__init__.py",
  "recipes-docs/source/recipes/**",
]
